<?php

namespace App\Support;

use App\Models\BoardingGallery;
use App\Models\BoardingProfile;
use App\Models\BreederGallery;
use App\Models\BreederProfile;
use App\Models\PetShopGallery;
use App\Models\PetShopProfile;
use App\Models\TrainerGallery;
use App\Models\TrainerProfile;
use App\Models\VetGallery;
use App\Models\VetProfile;
use App\Models\WelfareGallery;
use App\Models\WelfareProfile;

class ProfileConfig
{
    public static function all(): array
    {
        return [
            'breeder' => [
                'role' => 'breeder',
                'model' => BreederProfile::class,
                'slug_param' => 'breeder',
                'gallery_model' => BreederGallery::class,
                'gallery_foreign_key' => 'breeder_profile_id',
                'name_field' => 'name',
                'logo_path' => 'breeders/logos',
                'gallery_path' => 'breeders/gallery',
                'dashboard_view' => 'dashboard/breeder/index',
                'edit_view' => 'breeder/profile',
                'success_update' => 'Kennel profile updated successfully.',
                'success_create' => 'Kennel profile created successfully and is pending approval.',
                'success_created_admin' => 'Breeder profile created successfully.',
                'success_updated_admin' => 'Breeder profile updated successfully.',
                'success_deleted_admin' => 'Breeder profile deleted permanently.',
                'gallery_deleted' => 'Kennel image removed from gallery.',
                'gallery_image_deleted_admin' => 'Image removed from gallery.',
                'verification_toggled' => 'Verification status updated.',
                'activation_toggled' => 'Activation status updated.',
                'fillable_fields' => ['kennel_name', 'description', 'phone', 'email', 'address', 'state_id', 'city_id'],
                'with_relations' => ['state', 'city', 'gallery'],
                'admin_with' => ['user.role', 'state', 'city', 'gallery'],
                'admin_index_view' => 'admin/breeders/index',
                'admin_create_view' => 'admin/breeders/create',
                'admin_edit_view' => 'admin/breeders/edit',
                'admin_route_prefix' => 'breeders',
                'has_verified' => true,
                'available_users_role' => 'breeder',
                'available_users_relation' => 'breederProfile',
                'available_users_role_field' => 'role_id',
                'validation' => [
                    'user_id' => ['nullable', 'exists:users,id'],
                    'kennel_name' => ['required', 'string', 'max:255'],
                    'description' => ['nullable', 'string'],
                    'phone' => ['required', 'string', 'max:20'],
                    'email' => ['nullable', 'email', 'max:255'],
                    'facebook_url' => ['nullable', 'url', 'max:255'],
                    'instagram_url' => ['nullable', 'url', 'max:255'],
                    'twitter_url' => ['nullable', 'url', 'max:255'],
                    'youtube_url' => ['nullable', 'url', 'max:255'],
                    'state_id' => ['required', 'exists:states,id'],
                    'city_id' => ['required', 'exists:cities,id'],
                    'address' => ['required', 'string'],
                    'logo' => ['nullable', 'image', 'max:2048'],
                    'gallery.*' => ['nullable', 'image', 'max:2048'],
                ],
                'admin_filters' => ['is_verified', 'is_active', 'state_id', 'city_id'],
                'extra_data' => null,
            ],
            'vet' => [
                'role' => 'vet',
                'model' => VetProfile::class,
                'slug_param' => 'vet',
                'gallery_model' => VetGallery::class,
                'gallery_foreign_key' => 'vet_profile_id',
                'name_field' => 'name',
                'logo_path' => 'vets/logos',
                'gallery_path' => 'vets/gallery',
                'dashboard_view' => 'dashboard/vet/index',
                'edit_view' => 'dashboard/vet/profile',
                'success_update' => 'Clinic profile updated successfully.',
                'success_create' => 'Clinic profile created successfully and is pending approval.',
                'success_created_admin' => 'Veterinary clinic added successfully.',
                'success_updated_admin' => 'Veterinary clinic updated successfully.',
                'success_deleted_admin' => 'Veterinary clinic and all media deleted permanently.',
                'gallery_deleted' => 'Clinic photo removed from gallery.',
                'gallery_image_deleted_admin' => 'Gallery image removed.',
                'activation_toggled' => 'Activation status updated.',
                'fillable_fields' => ['clinic_name', 'description', 'phone', 'email', 'experience_years', 'address', 'state_id', 'city_id'],
                'with_relations' => ['state', 'city', 'gallery', 'services'],
                'admin_with' => ['state', 'city', 'user', 'gallery', 'services'],
                'admin_index_view' => 'admin/vets',
                'admin_create_view' => 'admin/vets/create',
                'admin_edit_view' => 'admin/vets/edit',
                'admin_route_prefix' => 'vets',
                'has_verified' => false,
                'available_users_role' => null,
                'available_users_relation' => 'vetProfile',
                'available_users_role_field' => 'role_id',
                'validation' => [
                    'user_id' => ['nullable', 'exists:users,id'],
                    'clinic_name' => ['required', 'string', 'max:255'],
                    'description' => ['nullable', 'string'],
                    'phone' => ['required', 'string', 'max:20'],
                    'email' => ['nullable', 'email', 'max:255'],
                    'experience_years' => ['nullable', 'integer', 'min:0', 'max:100'],
                    'state_id' => ['required', 'exists:states,id'],
                    'city_id' => ['required', 'exists:cities,id'],
                    'address' => ['required', 'string'],
                    'facebook_url' => ['nullable', 'url', 'max:255'],
                    'instagram_url' => ['nullable', 'url', 'max:255'],
                    'twitter_url' => ['nullable', 'url', 'max:255'],
                    'youtube_url' => ['nullable', 'url', 'max:255'],
                    'logo' => ['nullable', 'image', 'max:2048'],
                    'gallery.*' => ['nullable', 'image', 'max:2048'],
                    'services' => ['nullable', 'array'],
                    'services.*' => ['exists:vet_services,id'],
                ],
                'admin_filters' => ['is_active', 'state_id', 'city_id'],
                'extra_data' => 'services',
                'extra_data_model' => \App\Models\VetService::class,
            ],
            'trainer' => [
                'role' => 'trainer',
                'model' => TrainerProfile::class,
                'slug_param' => 'trainer',
                'gallery_model' => TrainerGallery::class,
                'gallery_foreign_key' => 'trainer_profile_id',
                'name_field' => 'name',
                'logo_path' => 'trainers/logos',
                'gallery_path' => 'trainers/gallery',
                'dashboard_view' => 'dashboard/trainer/index',
                'edit_view' => 'dashboard/trainer/profile',
                'success_update' => 'Trainer profile updated successfully.',
                'success_create' => 'Trainer profile created successfully and is pending approval.',
                'success_created_admin' => 'Trainer profile created successfully.',
                'success_updated_admin' => 'Trainer profile updated successfully.',
                'success_deleted_admin' => 'Trainer profile deleted permanently.',
                'gallery_deleted' => 'Trainer image removed from gallery.',
                'gallery_image_deleted_admin' => 'Image removed from gallery.',
                'activation_toggled' => 'Activation status updated.',
                'fillable_fields' => ['name', 'description', 'phone', 'email', 'experience_years', 'address', 'state_id', 'city_id'],
                'with_relations' => ['state', 'city', 'gallery', 'specializations'],
                'admin_with' => ['state', 'city', 'user', 'gallery', 'specializations'],
                'admin_index_view' => 'admin/trainers',
                'admin_create_view' => 'admin/trainers/create',
                'admin_edit_view' => 'admin/trainers/edit',
                'admin_route_prefix' => 'trainers',
                'has_verified' => false,
                'available_users_role' => 'trainer',
                'available_users_relation' => 'trainerProfile',
                'available_users_role_field' => 'role_id',
                'validation' => [
                    'user_id' => ['nullable', 'exists:users,id'],
                    'name' => ['required', 'string', 'max:255'],
                    'description' => ['nullable', 'string'],
                    'phone' => ['required', 'string', 'max:20'],
                    'email' => ['nullable', 'email', 'max:255'],
                    'experience_years' => ['nullable', 'integer', 'min:0', 'max:100'],
                    'state_id' => ['required', 'exists:states,id'],
                    'city_id' => ['required', 'exists:cities,id'],
                    'address' => ['required', 'string'],
                    'logo' => ['nullable', 'image', 'max:2048'],
                    'gallery.*' => ['nullable', 'image', 'max:2048'],
                    'specializations' => ['nullable', 'array'],
                    'specializations.*' => ['exists:trainer_specializations,id'],
                    'facebook_url' => ['nullable', 'url', 'max:255'],
                    'instagram_url' => ['nullable', 'url', 'max:255'],
                    'twitter_url' => ['nullable', 'url', 'max:255'],
                    'youtube_url' => ['nullable', 'url', 'max:255'],
                ],
                'admin_filters' => ['is_active', 'state_id', 'city_id'],
                'extra_data' => 'specializations',
                'extra_data_model' => \App\Models\TrainerSpecialization::class,
            ],
            'boarding' => [
                'role' => 'boarding',
                'model' => BoardingProfile::class,
                'slug_param' => 'boarding',
                'gallery_model' => BoardingGallery::class,
                'gallery_foreign_key' => 'boarding_profile_id',
                'name_field' => 'name',
                'logo_path' => 'boardings/logos',
                'gallery_path' => 'boardings/gallery',
                'dashboard_view' => 'dashboard/boarding/index',
                'edit_view' => 'dashboard/boarding/profile',
                'success_update' => 'Boarding profile updated successfully.',
                'success_create' => 'Boarding profile created successfully and is pending approval.',
                'success_created_admin' => 'Boarding profile created successfully.',
                'success_updated_admin' => 'Boarding profile updated successfully.',
                'success_deleted_admin' => 'Boarding profile deleted permanently.',
                'gallery_deleted' => 'Boarding image removed from gallery.',
                'gallery_image_deleted_admin' => 'Image removed from gallery.',
                'activation_toggled' => 'Activation status updated.',
                'fillable_fields' => ['name', 'description', 'phone', 'email', 'service_type', 'price_per_day', 'capacity', 'address', 'state_id', 'city_id'],
                'with_relations' => ['state', 'city', 'gallery'],
                'admin_with' => ['state', 'city', 'user', 'gallery'],
                'admin_index_view' => 'admin/boarding',
                'admin_create_view' => 'admin/boarding/create',
                'admin_edit_view' => 'admin/boarding/edit',
                'admin_route_prefix' => 'boarding',
                'has_verified' => false,
                'available_users_role' => 'boarding',
                'available_users_relation' => 'boardingProfile',
                'available_users_role_field' => 'role_id',
                'validation' => [
                    'user_id' => ['nullable', 'exists:users,id'],
                    'name' => ['required', 'string', 'max:255'],
                    'description' => ['nullable', 'string'],
                    'phone' => ['required', 'string', 'max:20'],
                    'email' => ['nullable', 'email', 'max:255'],
                    'service_type' => ['required', 'string', 'max:255'],
                    'price_per_day' => ['required', 'numeric', 'min:0'],
                    'capacity' => ['required', 'integer', 'min:1'],
                    'facebook_url' => ['nullable', 'url', 'max:255'],
                    'instagram_url' => ['nullable', 'url', 'max:255'],
                    'twitter_url' => ['nullable', 'url', 'max:255'],
                    'youtube_url' => ['nullable', 'url', 'max:255'],
                    'state_id' => ['required', 'exists:states,id'],
                    'city_id' => ['required', 'exists:cities,id'],
                    'address' => ['required', 'string'],
                    'logo' => ['nullable', 'image', 'max:2048'],
                    'gallery.*' => ['nullable', 'image', 'max:2048'],
                ],
                'admin_filters' => ['is_active', 'state_id', 'city_id'],
                'extra_data' => null,
            ],
            'welfare' => [
                'role' => 'welfare',
                'model' => WelfareProfile::class,
                'slug_param' => 'welfare',
                'gallery_model' => WelfareGallery::class,
                'gallery_foreign_key' => 'welfare_profile_id',
                'name_field' => 'name',
                'logo_path' => 'welfares/logos',
                'gallery_path' => 'welfares/gallery',
                'dashboard_view' => 'dashboard/welfare/index',
                'edit_view' => 'dashboard/welfare/profile',
                'success_update' => 'Welfare profile updated successfully.',
                'success_create' => 'Welfare profile created successfully and is pending approval.',
                'success_created_admin' => 'Welfare profile created successfully.',
                'success_updated_admin' => 'Welfare profile updated successfully.',
                'success_deleted_admin' => 'Welfare profile deleted permanently.',
                'gallery_deleted' => 'Welfare image removed from gallery.',
                'gallery_image_deleted_admin' => 'Image removed from gallery.',
                'activation_toggled' => 'Activation status updated.',
                'fillable_fields' => ['organization_name', 'description', 'phone', 'email', 'website', 'address', 'state_id', 'city_id'],
                'with_relations' => ['state', 'city', 'gallery'],
                'admin_with' => ['state', 'city', 'user', 'gallery'],
                'admin_index_view' => 'admin/welfare',
                'admin_create_view' => 'admin/welfare/create',
                'admin_edit_view' => 'admin/welfare/edit',
                'admin_route_prefix' => 'welfare',
                'has_verified' => false,
                'available_users_role' => 'welfare',
                'available_users_relation' => 'welfareProfile',
                'available_users_role_field' => 'role_id',
                'validation' => [
                    'user_id' => ['nullable', 'exists:users,id'],
                    'organization_name' => ['required', 'string', 'max:255'],
                    'description' => ['nullable', 'string'],
                    'phone' => ['required', 'string', 'max:20'],
                    'email' => ['nullable', 'email', 'max:255'],
                    'website' => ['nullable', 'url', 'max:255'],
                    'facebook_url' => ['nullable', 'url', 'max:255'],
                    'instagram_url' => ['nullable', 'url', 'max:255'],
                    'twitter_url' => ['nullable', 'url', 'max:255'],
                    'youtube_url' => ['nullable', 'url', 'max:255'],
                    'state_id' => ['required', 'exists:states,id'],
                    'city_id' => ['required', 'exists:cities,id'],
                    'address' => ['required', 'string'],
                    'logo' => ['nullable', 'image', 'max:2048'],
                    'gallery.*' => ['nullable', 'image', 'max:2048'],
                ],
                'admin_filters' => ['is_active', 'state_id', 'city_id'],
                'extra_data' => null,
            ],
            'pet-shop' => [
                'role' => 'pet-shop',
                'model' => PetShopProfile::class,
                'slug_param' => 'pet_shop',
                'gallery_model' => PetShopGallery::class,
                'gallery_foreign_key' => 'pet_shop_profile_id',
                'name_field' => 'name',
                'logo_path' => 'pet-shops/logos',
                'gallery_path' => 'pet-shops/gallery',
                'dashboard_view' => 'dashboard/pet-shop/index',
                'edit_view' => 'pet-shop/profile',
                'success_update' => 'Pet shop profile updated successfully.',
                'success_create' => 'Pet shop profile created successfully and is pending approval.',
                'success_created_admin' => 'Pet shop profile created successfully.',
                'success_updated_admin' => 'Pet shop profile updated successfully.',
                'success_deleted_admin' => 'Pet shop profile deleted permanently.',
                'gallery_deleted' => 'Pet shop image removed from gallery.',
                'gallery_image_deleted_admin' => 'Image removed from gallery.',
                'activation_toggled' => 'Activation status updated.',
                'fillable_fields' => ['shop_name', 'description', 'phone', 'email', 'website', 'address', 'state_id', 'city_id'],
                'with_relations' => ['state', 'city', 'gallery'],
                'admin_with' => ['state', 'city', 'user', 'gallery'],
                'admin_index_view' => 'admin/pet-shops',
                'admin_create_view' => 'admin/pet-shops/create',
                'admin_edit_view' => 'admin/pet-shops/edit',
                'admin_route_prefix' => 'pet-shops',
                'has_verified' => false,
                'available_users_role' => null,
                'available_users_relation' => 'petShopProfile',
                'available_users_role_field' => 'role_id',
                'validation' => [
                    'user_id' => ['nullable', 'exists:users,id'],
                    'shop_name' => ['required', 'string', 'max:255'],
                    'description' => ['nullable', 'string'],
                    'phone' => ['required', 'string', 'max:20'],
                    'email' => ['nullable', 'email', 'max:255'],
                    'website' => ['nullable', 'url', 'max:255'],
                    'facebook_url' => ['nullable', 'url', 'max:255'],
                    'instagram_url' => ['nullable', 'url', 'max:255'],
                    'twitter_url' => ['nullable', 'url', 'max:255'],
                    'youtube_url' => ['nullable', 'url', 'max:255'],
                    'state_id' => ['required', 'exists:states,id'],
                    'city_id' => ['required', 'exists:cities,id'],
                    'address' => ['required', 'string'],
                    'logo' => ['nullable', 'image', 'max:2048'],
                    'gallery.*' => ['nullable', 'image', 'max:2048'],
                ],
                'admin_filters' => ['is_active', 'state_id', 'city_id'],
                'extra_data' => null,
            ],
        ];
    }

    public static function get(string $type): ?array
    {
        return static::all()[$type] ?? null;
    }

    public static function isValid(string $type): bool
    {
        return isset(static::all()[$type]);
    }
}
